### ISSUE TITLE
IE11 Polyfill

### ISSUE THREAD

**Issue by sonnyk22** [MrFrontend/js-magazine#1]
To start, thank you for your great PWA article and the provided app.

Is there a way to configure the Service Worker internally in the app, either via a polyfill(s) or a flag, so that the app will work without the Service Worker caching in the older browsers such as IE10 or IE11?

**Comment by MrFrontend** [comment]
Hello Sonny,

Thank you for reaching out :)
Unfortunately there is no way to emulate / polyfill a Service Worker on older browsers due to the lack of options to intercept requests.
This could be partly achieved intercepting all the generated requests from JavaScript but you would be missing still a lot of requests generated by other elements (CSS files, <img tags, loading fonts, …).

In general what you could do to ensure the best load performance experience is to make sure you have a good cache strategy for your assets.
This is a great introduction article to it:
https://jakearchibald.com/2016/caching-best-practices/ <https://jakearchibald.com/2016/caching-best-practices/>

For non URL addressable resources you could use IndexedDB with a fall-back on Local Storage.
Take a look to http://dexie.org <http://dexie.org/>

Both techniques play well and work together with Service Workers, they are a graceful degradation for old browsers.

This is a quite generic answer, I hope is useful to you. Maybe there is something specific  you want to achieve and I did not cover ?

Best regards,
Antoni

**Comment by sonnyk22** [comment]
Thank you!
